project_id = "ovpvsysssqnvqwkqeybh"

[functions.analyze-question-image]
verify_jwt = false

[functions.classify-question]
verify_jwt = false

[functions.classify-questions-batch]
verify_jwt = false

[functions.export-taxonomy]
verify_jwt = false

[functions.import-taxonomy-v3]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
